# filepath: c:\repository\RedditPythonPractice\config_template.yaml
client_id: your_client_id
client_secret: your_client_secret
user_agent: your_user_agent
username: your_reddit_username
password: your_reddit_password
subreddit: your_subreddit